CREATE DATABASE JULY23;
USE JULY23;

SELECT * FROM CUSTOMERS

/*CRUD*/
--CREATE
---READ
---UPDATE
--DELETE

---REQUIREMENT
COLUMN NAME
RECORDS

CREATE TABLE STUDENT1(
ID INT PRIMARY KEY,
NAME VARCHAR(15),
PHONE BIGINT,
ADDRESS VARCHAR(MAX)
)

DROP TABLE STUDENTS

INSERT INTO STUDENTS (NAME,PHONE) VALUES('SHABANA',6203786742)

INSERT INTO STUDENTS VALUES(1,'SHABANA',6203786742)


SELECT * FROM STUDENT1



---HOW TO ADD COLUMN INTO EXISTING TABLE (ALTER COMMAND)

ALTER TABLE STUDENTS ADD ADDRES VARCHAR(MAX)


----DROP YOUR COLUMN

ALTER TABLE STUDENTS DROP COLUMN ADDRES 

BEGIN TRANSACTION
DELETE FROM STUDENTS
ROLLBACK TRANSACTION


SELECT * FROM STUDENTS


---DML DATAMANU PLATION LANGUAGE
INSERT
---INSERTING RECORDS WITH COLUMN AND VALUES SINGLE RECORDS
INSERT INTO STUDENT1 (ID,NAME,PHONE,ADDRESS) VALUES (1,'SHABANA' ,6742378534, 'LKO 34554 INDIA')


----
INSERT INTO STUDENT1 VALUES 
(3,'GIRIDHAR' ,6742378534, 'LKO 34554 INDIA'),
(4,'GIRIDHAR' ,6742378534, 'LKO 34554 INDIA'),
(5,'GIRIDHAR' ,6742378534, 'LKO 34554 INDIA'),
(6,'GIRIDHAR' ,6742378534, 'LKO 34554 INDIA')


SELECT * FROM STUDENT1

SELECT * INTO  STUDENTINFO 
FROM STUDENT1

SELECT * FROM STUDENTINFO
-----DELETE 
WHERE  --- IT WILL BE USEFULL INTO HANDLING SOMETHINNG BY CONDITION

DELETE FROM STUDENTINFO
WHERE ID =5
------UPDATE 
UPDATE

UPDATE STUDENTINFO 
SET NAME = 'VIBHA'
WHERE ID = 6


SELECT * FROM STUDENTINFO

DELETE FROM STUDENT1

TRUNCATE TABLE STUDENT1

DROP TABLE STUDENT1

USE [Premium Database]

---VIEW
----ITS USED FOR SECURITY PURPOSE OF YOUR DATABASE
---- DBO.CUSTOMERS

---FETCHING ALL CUSTOMER AND THEIR ORDER FROM DATABASE ALONG WITH SUM OF THEIR ORDER PRICE


CREATE OR ALTER VIEW CUSTOMER_CUM_ORDERS AS (
SELECT C.CustomerID,c.FirstName,O.OrderID, SUM(O.Total_order_amount	) as Valuess,
COUNT(O.ORDERID) AS CNT
FROM Orders O JOIN Customers C ON C.CustomerID=O.CustomerID
group by C.CustomerID,c.FirstName,O.OrderID)


SELECT * FROM CUSTOMER_CUM_ORDERS

----View creation
CREATE VIEW VIEW_NAME AS 
(SELECT * FROM Orders)

SELECT * FROM VIEW_NAME

CREATE ROLE 'SHABANA'
LOGIN
PASSWORD 'LETSBEANALYST123'
GRANT SELECT ON VIEW_NAME TO 'SHABANA'
---SECURITY
---SIMPLIFY THE QUERY
SELECT * FROM 

SELECT * FROM (SELECT C.CustomerID,c.FirstName,O.OrderID, SUM(O.Total_order_amount	) as Valuess
FROM Orders O JOIN Customers C ON C.CustomerID=O.CustomerID
group by C.CustomerID,c.FirstName,O.OrderID) D
JOIN (SELECT * FROM Customers WHERE CustomerID IN 
(57081,57082,57083,57084,57085,57086,57087,57088,57089)) S ON D.CustomerID = S.CustomerID




SELECT * FROM CUSTOMERS

SELECT * FROM CUSTOMER_CUM_ORDERS

-----TEMP TABLE
SYNTAX-- #TABLENAME

SELECT * INTO #MYTEMPTABLE FROM Customers

SELECT * FROM #MYTEMPTABLE


---CTE 
--COMMON TABLE EXPRESSION
SELECT * FROM ORDERS
WHERE Total_order_amount > (SELECT AVG(Total_order_amount) AS AVG_VALUE FROM Orders)

--SINGLE CTE
WITH AVG_VALUE AS 
(SELECT AVG(Total_order_amount) AS AVG_VALUE FROM Orders)
SELECT * FROM AVG_VALUE



WITH AVG_VALUE AS 
(
SELECT AVG(Total_order_amount) AS AVG_VALUE FROM Orders)
SELECT *
FROM Orders O JOIN AVG_VALUE C ON O.Total_order_amount > C.AVG_VALUE 
OR O.Total_order_amount < C.AVG_VALUE