USE COMPLETE_SQL_IN_10_DAYS
customers
orders
orderdetails

----CUSTOMERS

SELECT * FROM CUSTOMERS

---- HOW MANY CUSTOMERS ARE FROM NEWYORK
SELECT * FROM Customers
WHERE City = 'NEW YORK'  AND State = 'NEW YORK'


SELECT  FROM Customers
WHERE Country = 'Australia'  AND City = 'Brisbane'
ORDER BY FirstName DESC 

---QUERY OPTIMIZATION
------------1. WRITE ALL COLUMN NAME INSTEAD OF *


---GROUP BY --

SELECT * FROM Orders

---- RETURN CUSTOMER ID AND TOTAL QTY THEY ORDERED IN LAST 2021-01
SELECT CustomerID, COUNT(ORDERID) AS QTY
FROM Orders
WHERE OrderDate > '2021-01-01' AND OrderDate < '2021-02-01'
GROUP BY CustomerID
ORDER BY QTY DESC


---YEAR WISE ANALYSIS
SELECT * FROM Orders

SELECT YEAR(OrderDate) YEARS, COUNT(ORDERID) AS QTY
FROM Orders
GROUP BY YEAR(OrderDate)
ORDER BY QTY


---HAVING
-- FILTERING CLAUSE IN SQL 
